# Generated by Django 4.2.16 on 2024-10-05 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews_app.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews_app.price', verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='reviews_app.tagreview', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['-time_create'], name='reviews_app_time_cr_eaee23_idx'),
        ),
    ]
